title: Fundamental python
description: A website developed to aid students in learning Python.

# Conversion
markdown            : kramdown
highlighter         : rouge
liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Markdown Processors
kramdown:
  input             : GFM
